freebsd_instance:
  image: freebsd-12-1-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y git-lite curl wget zip cmake pkgconf libfm qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools qt5-multimedia
  test_script:
    - git submodule update --init --recursive
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - make -j$(sysctl -n hw.ncpu)
    - make DESTDIR=Filer.AppDir -j$(sysctl -n hw.ncpu) install
    - mkdir -p Filer.AppDir/usr/share/icons/hicolor/256x256/apps
    - cp ../src/icons/filer-256.png Filer.AppDir/usr/share/icons/hicolor/256x256/apps/filer.png
    - cp Filer.AppDir/usr/share/icons/hicolor/256x256/apps/filer.png Filer.AppDir/.DirIcon
    - ( cd Filer.AppDir/ ; ln -s usr/bin/Filer AppRun )
    - rm -rf Filer.AppDir/usr/include
    - mkdir -p Filer.AppDir/usr/lib
    - cp /usr/local/lib/libfm.so.4 Filer.AppDir/usr/lib
    - find Filer.AppDir/
    - zip --symlinks -r Filer_FreeBSD.zip Filer.AppDir/
    # curl --upload-file ./Filer_FreeBSD.zip https://transfer.sh/Filer_FreeBSD.zip
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
