freebsd_instance:
  image: freebsd-12-4-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[0b0897c4050477e6f87c8e7546d7abcd0a8ba9dae3ef30f3dee3855fab0a017c57d4a7e7a9d178bd49c55321bf6861ee]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-4-release-amd64
  stateful: false
  setup_script:
    - pkg install -y git-lite curl wget zip cmake pkgconf libfm qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools qt5-multimedia
  test_script:
    - git config --global http.sslVerify false # Workaround for: fatal: unable to access 'https://github.com/helloSystem/Sounds.git/': SSL certificate problem: unable to get local issuer certificate
    - git submodule update --init --recursive
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make DESTDIR=. -j$(sysctl -n hw.ncpu) install
    - cp /usr/local/lib/libfm.so.4 System/Filer.app/Resources
    - find System/Filer.app/
    - ( cd ./System ; zip --symlinks -r ../Filer_FreeBSD.zip Filer.app/ )
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
